**Applied Machine Learning Coursework**

In the first cell of code data is read from csv files, pre-processed, cleaned and tranformed. Then the data is ready for splitting into training and testing data.

In [13]:
import numpy as np
import pandas as pd
import nltk
nltk.download('stopwords')
from nltk import word_tokenize
from nltk.corpus import stopwords
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
#dataset uploaded to session storage and then read through pandas read csv function.
#Session storage expires after the window is closed.
#Kindly upload dataset files into session storage before executing the code.
data1 = pd.read_csv("processed_reviews_split_surnamesABCD_minimal.csv")
data2 = pd.read_csv("processed_reviews_split_surnamesEFGH_minimal.csv")
data3 = pd.read_csv("processed_reviews_split_surnamesIJKLM_minimal.csv")
data4 = pd.read_csv("processed_reviews_split_surnamesNOPQ_minimal.csv")
data5 = pd.read_csv("processed_reviews_split_surnamesRSTU_minimal.csv")
data6 = pd.read_csv("processed_reviews_split_surnamesVWXYZ_minimal.csv")
data = pd.concat([data1, data2, data3, data4, data5, data5, data6], ignore_index=True)
data = data.dropna()
data = data.drop_duplicates()
print(data.shape)
print(data['acceptance_status'].value_counts())
def textCleaning(text):
    remove_punctuation = [char for char in text if char not in string.punctuation]
    remove_punctuation = ''.join(remove_punctuation)
    return [word for word in remove_punctuation.split() if word.lower() not in stopwords.words("english")]
data.iloc[:,1].apply(textCleaning)
bowTransformer = CountVectorizer(analyzer=textCleaning).fit(data['text'])
bowTransformer.vocabulary_
textBow = bowTransformer.transform(data['text'])
tfidftranformer = TfidfTransformer().fit(textBow)
print(tfidftranformer)

textTfidf = tfidftranformer.transform(textBow)
print(textTfidf)
print(textTfidf.shape)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
(19574, 5)
Reject    11795
Accept     7779
Name: acceptance_status, dtype: int64
TfidfTransformer()
  (0, 69765)	0.015410668210625506
  (0, 69676)	0.01492117668272231
  (0, 69319)	0.038042075437836935
  (0, 69235)	0.08228419584020055
  (0, 69213)	0.09479505927603965
  (0, 69185)	0.0334287529008592
  (0, 68580)	0.051870991493859216
  (0, 68197)	0.016487304682780198
  (0, 68190)	0.017312986743635444
  (0, 66704)	0.05844813408469927
  (0, 66551)	0.04635818097833611
  (0, 66117)	0.0664693132190417
  (0, 66018)	0.091355246632686
  (0, 65683)	0.07490169035869262
  (0, 65655)	0.03468308778216253
  (0, 65418)	0.08382623572657076
  (0, 65097)	0.038928721613849915
  (0, 65037)	0.05147948208754048
  (0, 64821)	0.03031747985193076
  (0, 64680)	0.0438608189463233
  (0, 64444)	0.027030062434715788
  (0, 63930)	0.08878601668212978
  (0, 63405)	0.04118617858301399
  (0, 63245)	0.08878

In the second cell of code data is splitted into training and testing subsets. Data is fitted into Multinomial naive bayes model and prediction is made using the testing data. lastly accuracy, classification report and confusion matrix are printed.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(textTfidf, data['acceptance_status'], test_size = 0.25, random_state = 0)
modelNB = MultinomialNB().fit(X_train, y_train)
prediction = modelNB.predict(X_test)
print("Naive Bayes acceptance status prediction: \n", prediction)
print("The accuracy score of Naive Bayes acceptance status prediction is: \n",accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

print(confusion_matrix(y_test, prediction))

Naive Bayes acceptance status prediction: 
 ['Reject' 'Reject' 'Reject' ... 'Reject' 'Reject' 'Reject']
The accuracy score of Naive Bayes acceptance status prediction is: 
 0.6697997548017981
              precision    recall  f1-score   support

      Accept       1.00      0.15      0.26      1903
      Reject       0.65      1.00      0.79      2991

    accuracy                           0.67      4894
   macro avg       0.82      0.58      0.52      4894
weighted avg       0.79      0.67      0.58      4894

[[ 287 1616]
 [   0 2991]]


In the third cell of code data is splitted into training and testing subsets. Here the label/target is review score. Data is fitted into Multinomial naive bayes model and prediction is made using the testing data. lastly accuracy, classification report and confusion matrix are printed.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(textTfidf, data['review_score'], test_size = 0.25, random_state = 0)
modelNB = MultinomialNB().fit(X_train, y_train)
prediction = modelNB.predict(X_test)
print("Naive Bayes review score prediction: \n", prediction)
print("The accuracy score of Naive Bayes review score prediction is: \n",accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))

Naive Bayes review score prediction: 
 [6. 6. 6. ... 6. 6. 5.]
The accuracy score of Naive Bayes review score prediction is: 
 0.40375970576215775
              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00       131
         1.0       0.00      0.00      0.00        12
         2.0       0.00      0.00      0.00        93
         3.0       0.00      0.00      0.00       419
         4.0       0.61      0.34      0.44       928
         5.0       0.45      0.56      0.50       999
         6.0       0.33      0.88      0.48      1098
         7.0       0.67      0.15      0.25       878
         8.0       0.00      0.00      0.00       252
         9.0       0.00      0.00      0.00        76
        10.0       0.00      0.00      0.00         8

    accuracy                           0.40      4894
   macro avg       0.19      0.18      0.15      4894
weighted avg       0.40      0.40      0.34      4894

[[  0   0   0   0  17  35  68  11   0   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In the forth cell of code data is splitted into training and testing subsets. Data is fitted into Logistic regression model and prediction is made using the testing data. lastly accuracy, classification report and confusion matrix are printed.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(textTfidf, data['acceptance_status'], test_size = 0.25, random_state = 0)
modelLR = LogisticRegression().fit(X_train, y_train)
prediction = modelLR.predict(X_test)
print("Logistic Regression acceptance status prediction: \n", prediction)
print("The accuracy score of Logistic Regression acceptance status prediction is: \n",accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))

Logistic Regression acceptance status prediction: 
 ['Reject' 'Reject' 'Reject' ... 'Accept' 'Accept' 'Reject']
The accuracy score of Logistic Regression acceptance status prediction is: 
 0.8872088271352677
              precision    recall  f1-score   support

      Accept       0.93      0.77      0.84      1903
      Reject       0.87      0.96      0.91      2991

    accuracy                           0.89      4894
   macro avg       0.90      0.87      0.88      4894
weighted avg       0.89      0.89      0.88      4894

[[1463  440]
 [ 112 2879]]


In the fifth cell of code data is splitted into training and testing subsets. Here the label/target is confidence score Data is fitted into Multinomial naive bayes model and prediction is made using the testing data. lastly accuracy, classification report and confusion matrix are printed.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(textTfidf, data['confidence_score'], test_size = 0.25, random_state = 0)
modelLR = LogisticRegression().fit(X_train, y_train)
prediction = modelLR.predict(X_test)
print("Logistic Regression confidence score prediction: \n", prediction)
print("The accuracy score of Logistic Regression confidence_score prediction is: \n",accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))
print(confusion_matrix(y_test, prediction))

Logistic Regression confidence score prediction: 
 [4. 4. 4. ... 4. 5. 4.]
The accuracy score of Logistic Regression confidence_score prediction is: 
 0.6348590110339191
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        44
         2.0       0.91      0.04      0.07       256
         3.0       0.67      0.43      0.52      1261
         4.0       0.61      0.94      0.74      2455
         5.0       0.85      0.27      0.41       878

    accuracy                           0.63      4894
   macro avg       0.61      0.34      0.35      4894
weighted avg       0.68      0.63      0.59      4894

[[   0    0   17   26    1]
 [   0   10   76  167    3]
 [   0    0  546  697   18]
 [   0    1  122 2312   20]
 [   0    0   60  579  239]]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0